### PR TITLE
WIP trying to fix heroku

### PR DESCRIPTION
**Pull request by trayo**
did a bunch of crazy stuff and it was fixed by naming
`main.css` to main.css.scss`.

Some crazy issue with the pipeline.

### CODE REVIEW

**Comment by gregnar** [comment]
very concerned about the failing tests!!!

**Comment by trayo** [comment]
Yeah this is a work in progress that I might end up trashing.

**Comment by gregnar** [comment]
Just githubbin bro

**Comment by dalexj** [comment]
works fine locally

**Pull request closed without merging**
