### PR TITLE
Add simplecov increase coverage

### PR DESCRIPTION
**Pull request by trayo**
Most of what I did is in my commit messages. The only thing that remains untested is the `teams?` method in the application helper. It's functionality is a bit confusing and in the way it's being implemented.

Given that we have a table on the database called Team, a `teams?` method would say to me that it's checking if there are any actual teams, but the code of the method checks that the `request.path` is equal to `/teams` or, since it's a regex, `/team` (because "team" would still match). I've included the code here for reference. 

```
  def teams?
    !!(request.path =~ /teams/)
  end
```

### CODE REVIEW

**Comment by Tmee** [comment]
Its checking the url to see if we need to make the screen more mobile compatible.  The name might need a change.

**Comment by gregnar** [comment]
I've changed the method to this: 

`def unauthenticated_and_viewing_teams?`
     `!!(request.path =~ /teams/) && !current_user`
  `end`

Also, according to Rubular, /teams/ doesn't match "team", so we're good there.

**Comment by trayo** [comment]
Cool! I like that change. I think this will have to be tested when we start writing some high level integration tests. I assume that the line will get hit by default when we need to have a user log in in the test.

I was prying into the method and I was doing some weird stuff. I double checked the regex in pry and you are correct. I was changing the regex, not the string it was matching.

**Comment by dalexj** [comment]
ready to merge

**Comment by Tmee** [comment]
Thanks for this input guys, super helpful. Can both of you stop commenting on this repo, please?

**Pull request merged**
